{
    'name': 'POS Quick Payment',
    'version': '16.0',
    'summary': 'test',
    'description': 'test',
    'depends': [
        'point_of_sale', 'pos_edit_order_line',
        'pos_stock_available_online', 'login_pos_direct',
        'pos_cache', 'account_reconcile_oca'],
    'data': [
        'views/res_config_settings_view.xml',
        'views/res_partner_view.xml',
        'views/account_move_view.xml',
        'data/product_data.xml',
    ],
    "assets": {
            "point_of_sale.assets": [
                "pos_quick_payment_16/static/src/js/PaymentScreen.esm.js",
                "pos_quick_payment_16/static/src/xml/PaymentScreen.xml",
                "pos_quick_payment_16/static/src/js/ProductScreen.js",
                "pos_quick_payment_16/static/src/js/QuickPayButton.js",
                "pos_quick_payment_16/static/src/js/CreditPayButton.js",
                "pos_quick_payment_16/static/src/js/PartnerListScreen.js",
                "pos_quick_payment_16/static/src/js/PartnerLine.js",
                "pos_quick_payment_16/static/src/js/SuccessPopup.js",
                "pos_quick_payment_16/static/src/xml/SuccessPopup.xml",
                "pos_quick_payment_16/static/src/xml/QuickPayButton.xml",
                "pos_quick_payment_16/static/src/js/paymentCreditPopup.js",
                "pos_quick_payment_16/static/src/xml/paymentCreditPopup.xml",
                "pos_quick_payment_16/static/src/xml/CreditPayButton.xml",
                "pos_quick_payment_16/static/src/xml/PartnerListScreen.xml",
                #"pos_quick_payment_16/static/src/xml/CashMovePopup.xml",
                "pos_quick_payment_16/static/src/js/ReceipScreen.js",
                "pos_quick_payment_16/static/src/css/pos.scss",
               # "pos_quick_payment_16/static/src/xml/ActionpadWidget.xml",
                'pos_quick_payment_16/static/src/js/models.js',
            ],
        },
    'installable': True,
    'auto_install': False,
}
